---
chdir: /var/www/sandbox.hoccer.com/v3/grouper
user: www-data
group: www-data
environment: production
address: 0.0.0.0
port: 9311
timeout: 30
log: log/thin.log
pid: /var/run/thin/grouper.sandbox.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
daemonize: true
