---
chdir: /var/www/hoccer.com/v3/grouper
user: www-data
group: www-data
environment: production
address: 0.0.0.0
port: 9411
timeout: 30
log: log/thin.log
pid: /var/run/thin/grouper.production.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
daemonize: true
